### ISSUE TITLE
How to...

### ISSUE THREAD

**Issue by vbourgeois** [ariatemplates/atlas-hashspace-bridge#3]
Hello,

Is there any documentation to integrate the bridge in an existing HashSpace project?

Thanks.

**Comment by olaf-k** [comment]
Hi!
Not yet.  The code for the bridge has been completed but requires code reviewing, tests and indeed, documentation.  This should be part of a coming sprint, ideally the next one starting mid-september.

**Comment by vbourgeois** [comment]
OK, my internship will be over, so I won't be able to test it.

Thanks
